CREATE TABLE IF NOT EXISTS schema_migrations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  migration_name VARCHAR(255) NOT NULL,
  checksum CHAR(64) NOT NULL,
  applied_at BIGINT UNSIGNED NOT NULL,
  created_at BIGINT UNSIGNED NOT NULL,
  updated_at BIGINT UNSIGNED NOT NULL,
  is_delete TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uq_schema_migrations_name (migration_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS projects (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  name VARCHAR(120) NOT NULL,
  slug VARCHAR(140) NOT NULL,
  ram_available_threshold_percent DECIMAL(5,2) NOT NULL,
  disk_available_threshold_percent DECIMAL(5,2) NOT NULL,
  load_5_per_core_threshold DECIMAL(10,3) NOT NULL,
  heartbeat_interval_seconds INT UNSIGNED NOT NULL,
  heartbeat_grace_seconds INT UNSIGNED NOT NULL,
  created_at BIGINT UNSIGNED NOT NULL,
  updated_at BIGINT UNSIGNED NOT NULL,
  is_delete TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uq_projects_public_id (public_id),
  UNIQUE KEY uq_projects_slug (slug),
  KEY idx_projects_active (is_delete, name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS internal_users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  email VARCHAR(254) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL,
  failed_login_count INT UNSIGNED NOT NULL DEFAULT 0,
  locked_until BIGINT UNSIGNED NULL,
  last_login_at BIGINT UNSIGNED NULL,
  created_at BIGINT UNSIGNED NOT NULL,
  updated_at BIGINT UNSIGNED NOT NULL,
  is_delete TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uq_internal_users_public_id (public_id),
  UNIQUE KEY uq_internal_users_email (email),
  KEY idx_internal_users_active (is_delete, email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS user_sessions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  csrf_hash CHAR(64) NOT NULL,
  expires_at BIGINT UNSIGNED NOT NULL,
  last_seen_at BIGINT UNSIGNED NOT NULL,
  revoked_at BIGINT UNSIGNED NULL,
  user_agent_hash CHAR(64) NULL,
  ip_address VARCHAR(45) NULL,
  created_at BIGINT UNSIGNED NOT NULL,
  updated_at BIGINT UNSIGNED NOT NULL,
  is_delete TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uq_user_sessions_public_id (public_id),
  KEY idx_user_sessions_user (user_id, is_delete, expires_at),
  CONSTRAINT fk_user_sessions_user FOREIGN KEY (user_id) REFERENCES internal_users (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agents (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  project_id BIGINT UNSIGNED NOT NULL,
  server_name VARCHAR(120) NOT NULL,
  health_api_url VARCHAR(2048) NOT NULL,
  health_request_timeout_seconds INT UNSIGNED NOT NULL,
  apache_service_name VARCHAR(120) NOT NULL,
  credential_hash CHAR(64) NOT NULL,
  credential_hint VARCHAR(12) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'new',
  probable_cause VARCHAR(255) NULL,
  agent_version VARCHAR(40) NULL,
  last_heartbeat_at BIGINT UNSIGNED NULL,
  last_metrics_at BIGINT UNSIGNED NULL,
  last_validation_error VARCHAR(500) NULL,
  last_ram_available_percent DECIMAL(6,2) NULL,
  last_disk_available_percent DECIMAL(6,2) NULL,
  last_load_5_per_core DECIMAL(12,4) NULL,
  last_health_outcome VARCHAR(20) NULL,
  last_health_http_status_code SMALLINT UNSIGNED NULL,
  last_health_latency_ms INT UNSIGNED NULL,
  created_at BIGINT UNSIGNED NOT NULL,
  updated_at BIGINT UNSIGNED NOT NULL,
  is_delete TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uq_agents_public_id (public_id),
  UNIQUE KEY uq_agents_project_name (project_id, server_name),
  KEY idx_agents_project_status (project_id, is_delete, status),
  KEY idx_agents_due (is_delete, last_heartbeat_at),
  CONSTRAINT fk_agents_project FOREIGN KEY (project_id) REFERENCES projects (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS heartbeat_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  project_id BIGINT UNSIGNED NOT NULL,
  agent_id BIGINT UNSIGNED NOT NULL,
  received_at BIGINT UNSIGNED NOT NULL,
  has_payload TINYINT(1) NOT NULL,
  telemetry_valid TINYINT(1) NOT NULL,
  validation_error VARCHAR(500) NULL,
  created_at BIGINT UNSIGNED NOT NULL,
  updated_at BIGINT UNSIGNED NOT NULL,
  is_delete TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_heartbeat_agent_time (agent_id, received_at),
  KEY idx_heartbeat_project_time (project_id, received_at),
  CONSTRAINT fk_heartbeat_project FOREIGN KEY (project_id) REFERENCES projects (id),
  CONSTRAINT fk_heartbeat_agent FOREIGN KEY (agent_id) REFERENCES agents (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS metric_samples (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  project_id BIGINT UNSIGNED NOT NULL,
  agent_id BIGINT UNSIGNED NOT NULL,
  sequence_id BIGINT UNSIGNED NOT NULL,
  observed_at BIGINT UNSIGNED NOT NULL,
  received_at BIGINT UNSIGNED NOT NULL,
  agent_version VARCHAR(40) NOT NULL,
  cpu_count INT UNSIGNED NULL,
  load_1 DECIMAL(12,4) NULL,
  load_5 DECIMAL(12,4) NULL,
  load_15 DECIMAL(12,4) NULL,
  memory_total_bytes BIGINT UNSIGNED NULL,
  memory_available_bytes BIGINT UNSIGNED NULL,
  swap_total_bytes BIGINT UNSIGNED NULL,
  swap_free_bytes BIGINT UNSIGNED NULL,
  uptime_seconds BIGINT UNSIGNED NULL,
  health_checked_at BIGINT UNSIGNED NOT NULL,
  health_outcome VARCHAR(20) NOT NULL,
  health_http_status_code SMALLINT UNSIGNED NULL,
  health_latency_ms INT UNSIGNED NULL,
  health_error_code VARCHAR(40) NULL,
  health_error_message VARCHAR(500) NULL,
  top_processes_json JSON NOT NULL,
  created_at BIGINT UNSIGNED NOT NULL,
  updated_at BIGINT UNSIGNED NOT NULL,
  is_delete TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uq_metric_agent_sequence (agent_id, sequence_id),
  KEY idx_metric_agent_time (agent_id, received_at),
  KEY idx_metric_project_time (project_id, received_at),
  CONSTRAINT fk_metric_project FOREIGN KEY (project_id) REFERENCES projects (id),
  CONSTRAINT fk_metric_agent FOREIGN KEY (agent_id) REFERENCES agents (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS filesystem_samples (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  metric_sample_id BIGINT UNSIGNED NOT NULL,
  project_id BIGINT UNSIGNED NOT NULL,
  agent_id BIGINT UNSIGNED NOT NULL,
  observed_at BIGINT UNSIGNED NOT NULL,
  filesystem VARCHAR(255) NOT NULL,
  mount_point VARCHAR(512) NOT NULL,
  total_bytes BIGINT UNSIGNED NOT NULL,
  available_bytes BIGINT UNSIGNED NOT NULL,
  inode_used_percent DECIMAL(6,2) NULL,
  created_at BIGINT UNSIGNED NOT NULL,
  updated_at BIGINT UNSIGNED NOT NULL,
  is_delete TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_filesystem_agent_time (agent_id, observed_at),
  KEY idx_filesystem_metric (metric_sample_id),
  CONSTRAINT fk_filesystem_metric FOREIGN KEY (metric_sample_id) REFERENCES metric_samples (id) ON DELETE CASCADE,
  CONSTRAINT fk_filesystem_project FOREIGN KEY (project_id) REFERENCES projects (id),
  CONSTRAINT fk_filesystem_agent FOREIGN KEY (agent_id) REFERENCES agents (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS service_check_samples (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  metric_sample_id BIGINT UNSIGNED NOT NULL,
  project_id BIGINT UNSIGNED NOT NULL,
  agent_id BIGINT UNSIGNED NOT NULL,
  observed_at BIGINT UNSIGNED NOT NULL,
  service_name VARCHAR(120) NOT NULL,
  service_status VARCHAR(20) NOT NULL,
  created_at BIGINT UNSIGNED NOT NULL,
  updated_at BIGINT UNSIGNED NOT NULL,
  is_delete TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_service_agent_time (agent_id, observed_at),
  KEY idx_service_metric (metric_sample_id),
  CONSTRAINT fk_service_metric FOREIGN KEY (metric_sample_id) REFERENCES metric_samples (id) ON DELETE CASCADE,
  CONSTRAINT fk_service_project FOREIGN KEY (project_id) REFERENCES projects (id),
  CONSTRAINT fk_service_agent FOREIGN KEY (agent_id) REFERENCES agents (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS incidents (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL,
  project_id BIGINT UNSIGNED NOT NULL,
  agent_id BIGINT UNSIGNED NOT NULL,
  incident_type VARCHAR(50) NOT NULL,
  severity VARCHAR(20) NOT NULL,
  status VARCHAR(20) NOT NULL,
  probable_cause VARCHAR(255) NOT NULL,
  details_json JSON NOT NULL,
  opened_at BIGINT UNSIGNED NOT NULL,
  resolved_at BIGINT UNSIGNED NULL,
  last_notification_at BIGINT UNSIGNED NULL,
  created_at BIGINT UNSIGNED NOT NULL,
  updated_at BIGINT UNSIGNED NOT NULL,
  is_delete TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uq_incidents_public_id (public_id),
  KEY idx_incidents_project_status (project_id, is_delete, status, opened_at),
  KEY idx_incidents_agent_type (agent_id, incident_type, status),
  CONSTRAINT fk_incidents_project FOREIGN KEY (project_id) REFERENCES projects (id),
  CONSTRAINT fk_incidents_agent FOREIGN KEY (agent_id) REFERENCES agents (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS notification_outbox (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  project_id BIGINT UNSIGNED NOT NULL,
  incident_id BIGINT UNSIGNED NOT NULL,
  channel VARCHAR(20) NOT NULL,
  event_type VARCHAR(20) NOT NULL,
  destination VARCHAR(255) NULL,
  payload_json JSON NOT NULL,
  status VARCHAR(20) NOT NULL,
  attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
  next_attempt_at BIGINT UNSIGNED NOT NULL,
  sent_at BIGINT UNSIGNED NULL,
  last_error VARCHAR(500) NULL,
  created_at BIGINT UNSIGNED NOT NULL,
  updated_at BIGINT UNSIGNED NOT NULL,
  is_delete TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_outbox_due (is_delete, status, next_attempt_at),
  CONSTRAINT fk_outbox_project FOREIGN KEY (project_id) REFERENCES projects (id),
  CONSTRAINT fk_outbox_incident FOREIGN KEY (incident_id) REFERENCES incidents (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS audit_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NULL,
  project_id BIGINT UNSIGNED NULL,
  action VARCHAR(80) NOT NULL,
  entity_type VARCHAR(80) NOT NULL,
  entity_id VARCHAR(80) NULL,
  metadata_json JSON NOT NULL,
  created_at BIGINT UNSIGNED NOT NULL,
  updated_at BIGINT UNSIGNED NOT NULL,
  is_delete TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_audit_project_time (project_id, created_at),
  KEY idx_audit_user_time (user_id, created_at),
  CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES internal_users (id),
  CONSTRAINT fk_audit_project FOREIGN KEY (project_id) REFERENCES projects (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
