import { DEFAULT_AGENT_CHECKS, type AgentChecks } from "../../shared/contracts.js";

export interface AgentScriptInput {
  agentId: string;
  projectName: string;
  agentName: string;
  credential: string;
  centralApiUrl: string;
  healthApiUrl: string | null;
  checks?: AgentChecks;
  healthRequestTimeoutSeconds: number;
}

export const AGENT_VERSION = "1.3.0";
export const APACHE_AUTO_DETECT_LABEL = "auto-detect";

export function shellSingleQuote(value: string): string {
  return `'${value.replaceAll("'", `'\"'\"'`)}'`;
}

export function shellCommentValue(value: string): string {
  return value
    .replace(/[\u0000-\u001f\u007f\u2028\u2029]+/g, " ")
    .replace(/\s+/g, " ")
    .replaceAll("\\", "/")
    .trim();
}

export function cronForInterval(intervalSeconds: number, scriptPath: string): string {
  if (intervalSeconds % 60 !== 0) {
    throw new Error("Cron intervals must use whole minutes.");
  }

  const minutes = intervalSeconds / 60;
  if (minutes === 60) return `0 * * * * /bin/sh ${shellSingleQuote(scriptPath)}`;
  if (minutes < 1 || minutes > 30 || 60 % minutes !== 0) {
    throw new Error("Supported cron intervals are 1, 2, 3, 4, 5, 6, 10, 12, 15, 20, 30, or 60 minutes.");
  }
  return `*/${minutes} * * * * /bin/sh ${shellSingleQuote(scriptPath)}`;
}

export function normalizeHealthApiUrl(value: string): string {
  const url = new URL(value);
  if (url.protocol !== "http:" && url.protocol !== "https:") {
    throw new Error("health_api_url must use http or https.");
  }
  if (url.username || url.password) {
    throw new Error("health_api_url must not contain embedded credentials.");
  }
  url.hash = "";
  return url.toString();
}

export function generateAgentScript(input: AgentScriptInput): string {
  const checks = input.checks ?? DEFAULT_AGENT_CHECKS;
  if (checks.middleware_api && !input.healthApiUrl) throw new Error("Middleware API URL is required when monitoring is enabled.");
  const lines = [
    "#!/bin/sh",
    "# Server Check agent — generated by the central backoffice.",
    `# Project: ${shellCommentValue(input.projectName)}`,
    `# Agent: ${shellCommentValue(input.agentName)}`,
    "# This file contains a credential. Keep it owner-readable only (chmod 700).",
    "set -u",
    "umask 077",
    "",
    "DRY_RUN='0'",
    "case \"${1:-}\" in",
    "  '') ;;",
    "  --dry-run) DRY_RUN='1' ;;",
    "  *) printf '%s\\n' \"Usage: $0 [--dry-run]\" >&2; exit 2 ;;",
    "esac",
    "",
    `AGENT_VERSION=${shellSingleQuote(AGENT_VERSION)}`,
    `AGENT_ID=${shellSingleQuote(input.agentId)}`,
    `AGENT_CREDENTIAL=${shellSingleQuote(input.credential)}`,
    `CENTRAL_API_URL=${shellSingleQuote(input.centralApiUrl)}`,
    `HEALTH_API_URL=${shellSingleQuote(input.healthApiUrl ?? "")}`,
    `HEALTH_TIMEOUT=${shellSingleQuote(String(input.healthRequestTimeoutSeconds))}`,
    `CHECK_APACHE=${checks.apache ? "1" : "0"}`,
    `CHECK_NGINX=${checks.nginx ? "1" : "0"}`,
    `CHECK_MIDDLEWARE_API=${checks.middleware_api ? "1" : "0"}`,
    `APACHE_SERVICE_NAME=${shellSingleQuote(APACHE_AUTO_DETECT_LABEL)}`,
    "LOCK_DIR=\"${TMPDIR:-/tmp}/server-check-${AGENT_ID}.lock\"",
    "ERROR_FILE=\"${TMPDIR:-/tmp}/server-check-${AGENT_ID}.error\"",
    "DF_FILE=\"${TMPDIR:-/tmp}/server-check-${AGENT_ID}.df\"",
    "INODE_FILE=\"${TMPDIR:-/tmp}/server-check-${AGENT_ID}.inode\"",
    "",
    "if ! mkdir \"$LOCK_DIR\" 2>/dev/null; then",
    "  printf '%s\\n' \"Server Check agent is already running; skipping overlap.\" >&2",
    "  exit 0",
    "fi",
    "",
    "cleanup() {",
    "  rm -f \"$ERROR_FILE\" \"$DF_FILE\" \"$INODE_FILE\" 2>/dev/null || true",
    "  rmdir \"$LOCK_DIR\" 2>/dev/null || true",
    "}",
    "trap cleanup EXIT INT TERM",
    "",
    "now_ms() {",
    "  printf '%s000' \"$(date +%s)\"",
    "}",
    "",
    "json_escape() {",
    "  printf '%s' \"$1\" | awk 'BEGIN { ORS=\"\" } { if (NR > 1) printf \"\\\\n\"; gsub(/\\\\/, \"\\\\\\\\\"); gsub(/\"/, \"\\\\\\\"\"); gsub(/\\r/, \"\\\\r\"); gsub(/\\t/, \"\\\\t\"); printf \"%s\", $0 }'",
    "}",
    "",
    "number_or_null() {",
    "  case \"$1\" in",
    "    ''|*[!0-9.-]*) printf 'null' ;;",
    "    *) printf '%s' \"$1\" ;;",
    "  esac",
    "}",
    "",
    "CHECKED_AT=\"$(now_ms)\"",
    "HEALTH_OUTCOME='disabled'",
    "HEALTH_ERROR_CODE=''",
    "ERROR_MESSAGE=''",
    "HTTP_STATUS_JSON='null'",
    "LATENCY_MS=''",
    "if [ \"$CHECK_MIDDLEWARE_API\" = '1' ]; then",
    ": > \"$ERROR_FILE\"",
    "HEALTH_META=\"$(curl --silent --show-error --output /dev/null --write-out '%{http_code}|%{time_total}' --max-time \"$HEALTH_TIMEOUT\" \"$HEALTH_API_URL\" 2>\"$ERROR_FILE\")\"",
    "CURL_EXIT=$?",
    "HTTP_STATUS=\"$(printf '%s' \"$HEALTH_META\" | awk -F'|' '{print $1}')\"",
    "TIME_TOTAL=\"$(printf '%s' \"$HEALTH_META\" | awk -F'|' '{print $2}')\"",
    "LATENCY_MS=\"$(awk -v seconds=\"$TIME_TOTAL\" 'BEGIN { if (seconds ~ /^[0-9.]+$/) printf \"%d\", seconds * 1000 }')\"",
    "ERROR_MESSAGE=\"$(head -c 400 \"$ERROR_FILE\" 2>/dev/null | tr '\\r\\n' ' ')\"",
    "HEALTH_OUTCOME='unhealthy'",
    "HEALTH_ERROR_CODE='unknown_error'",
    "HTTP_STATUS_JSON='null'",
    "",
    "if [ \"$CURL_EXIT\" -eq 0 ] && [ \"$HTTP_STATUS\" = '200' ]; then",
    "  HEALTH_OUTCOME='healthy'",
    "  HEALTH_ERROR_CODE=''",
    "  ERROR_MESSAGE=''",
    "  HTTP_STATUS_JSON='200'",
    "elif [ \"$CURL_EXIT\" -eq 0 ]; then",
    "  HEALTH_ERROR_CODE='http_status_error'",
    "  HTTP_STATUS_JSON=\"$(number_or_null \"$HTTP_STATUS\")\"",
    "else",
    "  case \"$CURL_EXIT\" in",
    "    6) HEALTH_ERROR_CODE='dns_error' ;;",
    "    7) HEALTH_ERROR_CODE='connection_error' ;;",
    "    28) HEALTH_ERROR_CODE='timeout' ;;",
    "    35|51|58|60) HEALTH_ERROR_CODE='tls_error' ;;",
    "    *) HEALTH_ERROR_CODE='unknown_error' ;;",
    "  esac",
    "fi",
    "",
    "fi",
    "",
    "MEMORY_TOTAL_KB=\"$(awk '/^MemTotal:/ {print $2}' /proc/meminfo 2>/dev/null)\"",
    "MEMORY_AVAILABLE_KB=\"$(awk '/^MemAvailable:/ {print $2}' /proc/meminfo 2>/dev/null)\"",
    "SWAP_TOTAL_KB=\"$(awk '/^SwapTotal:/ {print $2}' /proc/meminfo 2>/dev/null)\"",
    "SWAP_FREE_KB=\"$(awk '/^SwapFree:/ {print $2}' /proc/meminfo 2>/dev/null)\"",
    "MEMORY_TOTAL_BYTES=\"$(awk -v value=\"$MEMORY_TOTAL_KB\" 'BEGIN { if (value ~ /^[0-9]+$/) printf \"%.0f\", value * 1024 }')\"",
    "MEMORY_AVAILABLE_BYTES=\"$(awk -v value=\"$MEMORY_AVAILABLE_KB\" 'BEGIN { if (value ~ /^[0-9]+$/) printf \"%.0f\", value * 1024 }')\"",
    "SWAP_TOTAL_BYTES=\"$(awk -v value=\"$SWAP_TOTAL_KB\" 'BEGIN { if (value ~ /^[0-9]+$/) printf \"%.0f\", value * 1024 }')\"",
    "SWAP_FREE_BYTES=\"$(awk -v value=\"$SWAP_FREE_KB\" 'BEGIN { if (value ~ /^[0-9]+$/) printf \"%.0f\", value * 1024 }')\"",
    "CPU_COUNT=\"$(getconf _NPROCESSORS_ONLN 2>/dev/null || true)\"",
    "LOAD_1=\"$(awk '{print $1}' /proc/loadavg 2>/dev/null)\"",
    "LOAD_5=\"$(awk '{print $2}' /proc/loadavg 2>/dev/null)\"",
    "LOAD_15=\"$(awk '{print $3}' /proc/loadavg 2>/dev/null)\"",
    "UPTIME_SECONDS=\"$(awk '{printf \"%d\", $1}' /proc/uptime 2>/dev/null)\"",
    "",
    "df -PkP -x tmpfs -x devtmpfs >\"$DF_FILE\" 2>/dev/null || df -PkP >\"$DF_FILE\" 2>/dev/null || : >\"$DF_FILE\"",
    "df -PiP -x tmpfs -x devtmpfs >\"$INODE_FILE\" 2>/dev/null || df -PiP >\"$INODE_FILE\" 2>/dev/null || : >\"$INODE_FILE\"",
    "FILESYSTEMS_JSON=\"$(awk '",
    "  function escape_json(value) { gsub(/\\\\/, \"\\\\\\\\\", value); gsub(/\"/, \"\\\\\\\"\", value); return value }",
    "  NR == FNR { if (FNR > 1) { gsub(/%/, \"\", $5); inode[$6] = $5 } next }",
    "  FNR == 1 { printf \"[\"; next }",
    "  count < 32 && $2 ~ /^[0-9]+$/ && $4 ~ /^[0-9]+$/ {",
    "    if (count++) printf \",\"",
    "    inode_value = (($6 in inode) && inode[$6] ~ /^[0-9.]+$/) ? inode[$6] : \"null\"",
    "    printf \"{\\\"filesystem\\\":\\\"%s\\\",\\\"mount_point\\\":\\\"%s\\\",\\\"total_bytes\\\":%.0f,\\\"available_bytes\\\":%.0f,\\\"inode_used_percent\\\":%s}\", escape_json($1), escape_json($6), $2 * 1024, $4 * 1024, inode_value",
    "  }",
    "  END { if (NR == 0) printf \"[\"; printf \"]\" }",
    "' \"$INODE_FILE\" \"$DF_FILE\")\"",
    "",
    "systemd_state() {",
    "  SERVICE_STATE=\"$(systemctl show \"$1.service\" --property=ActiveState --value 2>/dev/null || true)\"",
    "  case \"$SERVICE_STATE\" in",
    "    active|reloading) printf 'active' ;;",
    "    inactive|failed|deactivating) printf 'inactive' ;;",
    "    *) printf 'unknown' ;;",
    "  esac",
    "}",
    "APACHE_STATUS='disabled'",
    "if [ \"$CHECK_APACHE\" = '1' ]; then",
    "  APACHE_STATUS='unknown'",
    "  if [ -x '/opt/lampp/lampp' ]; then",
    "    APACHE_SERVICE_NAME='lampp-apache'",
    "    LAMPP_STATUS=\"$(LC_ALL=C /opt/lampp/lampp status 2>/dev/null || true)\"",
    "    case \"$LAMPP_STATUS\" in",
    "      *'Apache is not running.'*) APACHE_STATUS='inactive' ;;",
    "      *'Apache is running.'*) APACHE_STATUS='active' ;;",
    "    esac",
    "  elif command -v systemctl >/dev/null 2>&1; then",
    "    for APACHE_CANDIDATE in apache2 httpd; do",
    "      APACHE_LOAD_STATE=\"$(systemctl show \"${APACHE_CANDIDATE}.service\" --property=LoadState --value 2>/dev/null || true)\"",
    "      if [ \"$APACHE_LOAD_STATE\" = 'loaded' ]; then",
    "        APACHE_SERVICE_NAME=\"$APACHE_CANDIDATE\"",
    "        APACHE_STATUS=\"$(systemd_state \"$APACHE_CANDIDATE\")\"",
    "        break",
    "      fi",
    "    done",
    "  fi",
    "fi",
    "NGINX_STATUS='disabled'",
    "if [ \"$CHECK_NGINX\" = '1' ]; then",
    "  NGINX_STATUS='unknown'",
    "  if command -v systemctl >/dev/null 2>&1; then",
    "    NGINX_LOAD_STATE=\"$(systemctl show nginx.service --property=LoadState --value 2>/dev/null || true)\"",
    "    if [ \"$NGINX_LOAD_STATE\" = 'loaded' ]; then NGINX_STATUS=\"$(systemd_state nginx)\"; fi",
    "  fi",
    "  if [ \"$NGINX_STATUS\" = 'unknown' ] && command -v pgrep >/dev/null 2>&1; then",
    "    if pgrep -x nginx >/dev/null 2>&1; then",
    "      NGINX_STATUS='active'",
    "    elif command -v nginx >/dev/null 2>&1; then",
    "      NGINX_STATUS='inactive'",
    "    fi",
    "  fi",
    "fi",
    "",
    "TOP_PROCESSES_JSON=\"$(ps -eo comm=,%cpu=,%mem= --sort=-%cpu 2>/dev/null | awk 'NR <= 5 { command=$1; gsub(/\\\\/, \"\\\\\\\\\", command); gsub(/\"/, \"\\\\\\\"\", command); if (count++) printf \",\"; printf \"{\\\"command\\\":\\\"%s\\\",\\\"cpu_percent\\\":%s,\\\"memory_percent\\\":%s}\", command, $2 + 0, $3 + 0 } END { if (count == 0) printf \"\" }')\"",
    "TOP_PROCESSES_JSON=\"[$TOP_PROCESSES_JSON]\"",
    "OBSERVED_AT=\"$(now_ms)\"",
    "SEQUENCE_ID=\"$OBSERVED_AT\"",
    "ERROR_CODE_JSON='null'",
    "ERROR_MESSAGE_JSON='null'",
    "if [ -n \"$HEALTH_ERROR_CODE\" ]; then ERROR_CODE_JSON=\"\\\"$(json_escape \"$HEALTH_ERROR_CODE\")\\\"\"; fi",
    "if [ -n \"$ERROR_MESSAGE\" ]; then ERROR_MESSAGE_JSON=\"\\\"$(json_escape \"$ERROR_MESSAGE\")\\\"\"; fi",
    "",
    "PAYLOAD=\"$(cat <<JSON",
    "{\"sequence_id\":$SEQUENCE_ID,\"observed_at\":$OBSERVED_AT,\"agent_version\":\"$AGENT_VERSION\",\"health_probe\":{\"checked_at\":$CHECKED_AT,\"outcome\":\"$HEALTH_OUTCOME\",\"http_status_code\":$HTTP_STATUS_JSON,\"latency_ms\":$(number_or_null \"$LATENCY_MS\"),\"error_code\":$ERROR_CODE_JSON,\"error_message\":$ERROR_MESSAGE_JSON},\"metrics\":{\"cpu_count\":$(number_or_null \"$CPU_COUNT\"),\"load_1\":$(number_or_null \"$LOAD_1\"),\"load_5\":$(number_or_null \"$LOAD_5\"),\"load_15\":$(number_or_null \"$LOAD_15\"),\"memory_total_bytes\":$(number_or_null \"$MEMORY_TOTAL_BYTES\"),\"memory_available_bytes\":$(number_or_null \"$MEMORY_AVAILABLE_BYTES\"),\"swap_total_bytes\":$(number_or_null \"$SWAP_TOTAL_BYTES\"),\"swap_free_bytes\":$(number_or_null \"$SWAP_FREE_BYTES\"),\"uptime_seconds\":$(number_or_null \"$UPTIME_SECONDS\")},\"filesystems\":$FILESYSTEMS_JSON,\"top_processes\":$TOP_PROCESSES_JSON,\"service_checks\":{\"apache\":{\"service_name\":\"$(json_escape \"$APACHE_SERVICE_NAME\")\",\"status\":\"$APACHE_STATUS\"},\"nginx\":{\"service_name\":\"nginx\",\"status\":\"$NGINX_STATUS\"}}}",
    "JSON",
    ")\"",
    "",
    "if [ \"$DRY_RUN\" = '1' ]; then",
    "  printf '%s\\n' \"$PAYLOAD\"",
    "  exit 0",
    "fi",
    "",
    "if ! printf '%s' \"$PAYLOAD\" | curl --silent --show-error --fail --max-time 20 --retry 2 --retry-delay 1 --request POST --header 'Content-Type: application/json' --header \"Authorization: Bearer $AGENT_CREDENTIAL\" --data-binary @- \"$CENTRAL_API_URL\" >/dev/null; then",
    "  printf '%s\\n' \"Server Check could not report to the central API.\" >&2",
    "  exit 1",
    "fi",
    "",
    "printf '%s\\n' \"Server Check heartbeat delivered.\"",
    ""
  ];

  return `${lines.join("\n")}\n`;
}
